package by.study.news.controller;

public enum CommandName {
	NEWS_LIST, ADD_ARTICLE_PAGE, EDIT_ARTICLE_PAGE,  
	
	ADD_ARTICLE, EDIT_ARTICLE,
	
	VIEW_ARTICLE, DELETE_ARTICLE, DELETE_MARKED, 
	
	
	
	GO_TO_REGISTRATION_PAGE, GO_TO_SIGN_IN_PAGE,
	
	GO_TO_REGISTRATION_PAGE_AR,
	
	
	ADD_USER
}
